### ISSUE TITLE
멘토링이 필요한 질문거리 정리

### ISSUE THREAD

**Issue by joohongpark** [jinbekim/SQL#7]
- SQL의 `CASE` 식과 일반적인 프로그래밍 언어의 `if` 제어문과의 차이
  - 저희도 잘 몰겠슴둥...
- 쿼리문 내 `GROUP BY` 를 사용할 때 `SELECT`에 사용할 수 있는 컬럼이 제한되는 이유
  - DB 버전이나 DBMS에 따라 다르게 동작됨. 에러가 나거나 안나거나
- SQL 언어에서 식(expresion)을 지양해야 하는 이유
  - 식은 CPU 사용을 많이 하고 문은 I/O 접근을 많이하기 때문이라고 추측함.

**Comment by jinbekim** [comment]
학생의 입장에서 sql을 효과적 효율적으로 공부하는 방법!

**Comment by jinbekim** [comment]
db 공부하기 좋은 자료 추천

**Comment by jinbekim** [comment]
### 스터디를 이루고 싶은 목표가 무엇인지?
### RDBMS가 전부는 아니다.
### DBA, 개발자, 컨설팅 기
### 모델링 학습
### 수요자의 니즈를 파악
### 영어 공부가 중요하다. 미리미
### 기본기가 중요하다.
등등
결론 
- 스터디원 중 DBA가 되고 싶은 사람은 없기에 기존에 진행하던 방식을 계속해서 진행하지 않고,
남은 내용은 빠르게 훑고, 다른 학업에 열중 하기로 합의.
